config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  get 'signup',    to: 'users#new'
  get 'profile',   to: 'users#show'
  get 'login',     to: 'sessions#new'
  post 'login',    to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :events
  resources :invitations
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator,   class_name:  'User'
  has_many :invitations, foreign_key: :event_id,
                         dependent:   :destroy
  has_many :attendees,   through:     :invitations,
                         source:      :attendee,
                         dependent:   :destroy

  validates_presence_of :title, :description, :location, :date, :time
  validates :description, length: { in: 5..600 }
  validates :location,    length: { maximum: 40 }
  validates :title,       length: { in: 4..50 }

  validate :valid_date
  validate :valid_time

  default_scope       { order(date: :asc) }
  scope :upcoming, -> { where('date >= ?', Time.zone.today) }
  scope :past,     -> { where('date < ?', Time.zone.today) }

  def valid_date
    return unless date && date < Time.zone.today
    errors.add(:event_date, "can't be in the past")
  end

  def valid_time
    return unless date == Time.zone.today &&
                  time && time.hour < Time.zone.now.hour
    errors.add(:event_time, "can't be in the past")
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :event
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_remember_token
  before_save { email.downcase! }
  before_save { name.capitalize! }

  has_many :created_events,  class_name: Event,
                             foreign_key: :creator_id,
                             dependent:   :destroy

  has_many :attended_events, through: :invitations,
                             source:  :event

  has_many :invitations,     foreign_key: :attendee_id,
                             dependent:   :destroy

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_presence_of :name, :email, :password
  validates :name,  length:     { maximum: 30 }
  validates :email, length:     { maximum: 255 },
                    format:     { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { in: 6..20 }, allow_nil: true
  has_secure_password

  def self.create_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def generate_remember_token
      self.remember_token = User.digest(User.create_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def logged_in_user
    return if logged_in?
    flash[:danger] = 'Please log in to proceed.'
    redirect_to login_url
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:create, :new]
  before_action :event_creator,  only: [:edit, :update, :destroy]
  before_action :find_event,     only: [:edit, :update, :destroy, :show]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = 'Created event!'
      redirect_to @event
    else
      render :new
    end
  end

  def index
    @upcoming_events = Event.upcoming.paginate(page: params[:upcoming_events],
                                               per_page: 8)
    @past_events = Event.past.paginate(page: params[:past_events],
                                       per_page: 8)
  end

  def edit
  end

  def update
    @event.update_attributes(event_params)
    if @event.save
      flash[:success] = 'Updated!'
      redirect_to @event
    else
      flash[:danger] = 'Problem with your form'
      render :edit
    end
  end

  def show
  end

  def destroy
    if @event.destroy
      flash[:success] = 'Deleted!'
      redirect_to events_path
    else
      flash[:danger] = 'Failed to delete'
      render @event
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :date, :time)
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def event_creator
    @event = Event.find(params[:id])
    return if current_user == @event.creator
    flash[:danger] = 'I can\'t let you do that, Dave'
    redirect_to root_url
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    @event = Event.find(params[:invitation][:event_id])
    invitation = current_user.invitations.build(event_id: @event.id)
    if invitation.save
      flash[:success] = 'You are attending this event!'
      redirect_to :back
    else
      flash[:danger] = 'There is a temporary problem in our servers.'
      redirect_to :back
    end
  end

  def destroy
    invitation = Invitation.find(params[:id])
    current_user.invitations.destroy invitation
    flash[:success] = 'You are no longer attending this event'
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    return unless logged_in?
    flash[:info] = 'You are already logged in.'
    redirect_to root_url
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = 'Connected!'
      redirect_to root_path
    else
      flash.now[:danger] = 'Wrong user/password'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: :show

  def new
    redirect_to root_url if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Registered!'
      log_in @user
      redirect_to root_url
    else
      flash.now[:danger] = 'Something is wrong with your form'
      render :new
    end
  end

  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
    @attended_events = @user.attended_events.paginate(page: params[:page],
                                                      per_page: 8)
    @created_events = @user.created_events.paginate(page: params[:page],
                                                    per_page: 8)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page(path)
    'current' if current_page?(path)

    # TODO: make it not buggy:
    # 'current' if request.url.include?(path)
  end

  # helper method following DRY principle. The string is the same
  # in both the hyperlink-text and the data-hover html attribute.
  def create_nav_link(string, path, method)
    link_to string, path, data: { hover: string }, method: method
  end

  # helper method following DRY principle using both mentioned methods.
  # consider that both create_nav_link and current_page methods are using the
  # same path variable.
  def create_nav_item(string, path, method = nil)
    content_tag :li, create_nav_link(string, path, method),
                class: current_page(path)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    remember_token = User.create_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    @current_user = user
  end

  def log_out
    flash[:info] = 'Disconnected!'
    cookies.delete(:remember_token)
    @current_user = nil
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def current_user=(user)
    @current_user = user
  end

  def logged_in?
    current_user.present?
  end
end

app/views/events/_event.html.erb
<div class="col-md-6">
  <div class="event-details">
    <h3> <%= link_to event.title, event_path(event), style: 'text-decoration: none' %> </h3>
    <div class="description">
      <h5>
        <%= event.description[0..120] %><% if event.description.size >= 120 %>...<% end %>
      </h5>
    </div>
    <div class="arrival-details">
      <h5><%= event.location %></h5>
      <h5><%= event.date.strftime("%d/%m/%Y") %> <%= event.time.strftime("at %I:%M %p") %></h5>
      <h5>
        Event by:
        <%= link_to event.creator.name, user_path(event.creator) %>
      </h5>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', required: true %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control ", size:'20x3', required: true %>
  <br>
  <%= f.label :location %>
  <%= f.text_field :location, class: "form-control", required: true %>
  <br>
  <div class="row">
    <div class="col-sm-4 col-xs-6">
      <%= f.label :time %>
      <div class="input-group">
        <%= f.text_field :time, class: "form-control timepicker", required: true %>
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-time"></i>
        </span>
      </div>
    </div>
    <div class="col-sm-4 col-sm-offset-4 col-xs-6">
      <%= f.label :date %>
      <div class="input-group">
        <%= f.text_field :date, class: "form-control datepicker", required: true %>
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-calendar"></i>
        </span>
      </div>
    </div>
  </div>
  <br>
  <%= f.submit @event.new_record? ? "Create event" : "Edit event", class: "btn btn-primary",
      data: { disable_with: 'Submitting...' } %>
<% end %>

app/views/events/_initialized_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function () {
    $('.datepicker').pickadate({
      formatSubmit: 'dd/mm/yyyy',
      hiddenName: true
    });
    $('.timepicker').pickatime({
      formatSubmit: 'HH:i',
      hiddenName: true,
      min: [6,30],
      max: [23,30]
    });
  });
</script>

app/views/events/edit.html.erb
<h1>Edit event</h1>
<%= render 'initialized_form' %>

app/views/events/index.html.erb
<section class="events-wrapper">
  <h1>Events list</h1>
  <ul class="tabs">
    <li class="active">Upcoming events</li>
    <li>Previous Events</li>
  </ul>

  <ul class="tab__content">
    <li class="active">
      <div class="content__wrapper">
        <div class="row">
          <% if @upcoming_events.present? %>
            <%= render @upcoming_events %>
            <%= will_paginate @upcoming_events, class: "text-center" %>
          <% else %>
            <p>Nothing to see here, yet.</p>
          <% end %>
        </div>
      </div>
    </li>
    <li>
      <div class="content__wrapper">
        <div class="row">
          <% if @past_events.present? %>
            <%= render @past_events %>
            <%= will_paginate @past_events, class: "text-center" %>
          <% else %>
            <p>Nothing to see here, yet.</p>
          <% end %>
        </div>
      </div>
    </li>
  </ul>
</section>

app/views/events/new.html.erb
<h1>New event</h1>
<%= render 'initialized_form' %>

app/views/events/show.html.erb
<div class="container-fluid">
  <h1><%= @event.title %></h1>
  <br>
  <div class="row">
    <% if current_user.present? %>
      <% if current_user == @event.creator %>
        <div class="col-md-2 col-md-offset-4 col-sm-12">
          <%= link_to "Edit", edit_event_path(@event), class: 'cool-btn info-btn' %>
        </div>
        <div class="col-md-2 col-sm-12">
          <%= link_to "Delete Event", @event, method: :delete,
          data: {confirm: 'Delete?'},
          class: 'cool-btn danger-btn' %>
        </div>
      <% else %>
        <% if current_user.attended_events.include? @event %>
          <div class="col-sm-12">
            <%= link_to "Cancel Attendance", current_user.invitations.find_by(event_id: @event.id),
            method: :delete, data: {confirm: "Are you sure?"},
            class: 'cool-btn danger-btn attendance-btn' %>
          </div>
        <% else %>
          <%= form_for(current_user.invitations.build(event_id: @event.id)) do |f| %>
            <%= f.hidden_field :event_id, value: @event.id %>
            <%= f.submit "Attend", class: 'cool-btn success-btn attendance-btn', id:"attend-button" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <br><br>
  <div class="row">
    <div class="col-md-2 col-md-offset-5 ">
      <h4>Users attending: </h4>
      <ul class="list-group">
        <% @event.attendees.each do |attendee| %>
            <li class="list-group-item">
              <%= link_to attendee.name, user_path(attendee) %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_anti-fouc.html.erb
<style type="text/css">.no-fouc{display:none;}</style>
<script type="text/javascript">
document.documentElement.className='no-fouc';
document.addEventListener('DOMContentLoaded',function(event){document.documentElement.classList.remove("no-fouc");});
</script>

app/views/layouts/_anti_fouc.html.erb
<style type="text/css">.no-fouc{display:none;}</style>
<script type="text/javascript">
document.documentElement.className='no-fouc';
document.addEventListener('DOMContentLoaded',function(event){document.documentElement.classList.remove("no-fouc");});
</script>

app/views/layouts/_footer.html.erb
<footer>
  <div class="details">Aviv Levinsky &copy;</div>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <header>
    <nav class="navbar">
      <ul class="navbar_fx">
        <%= create_nav_item('Home', root_url) %>
        <% if logged_in? %>
          <%= create_nav_item('Profile', profile_path) %>
          <%= create_nav_item('Events', events_path) %>
          <%= create_nav_item('Create event', new_event_path) %>
          <%= create_nav_item('Logout', logout_path, :delete) %>
        <% else %>
          <%= create_nav_item('Events', events_path) %>
          <%= create_nav_item('Login', login_path) %>
          <%= create_nav_item('Sign up', signup_path) %>
        <% end %>
      </ul>
    </nav>
  </header>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_webapp_meta_tags.html.erb
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="theme-color" content="#5288ff" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>Private Events</title>
    <%= render 'layouts/webapp_meta_tags' %>
    <%= stylesheet_link_tag 'application',
                            '//fonts.googleapis.com/css?family=Roboto:500,400,300',
                             media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', async: Rails.env.production?,
                               'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if flash.present? %>
      <div class="container">
        <% flash.each do |type, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{type}") %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <%# debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      There are <%= pluralize(object.errors.count, "problem") %> with your form.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_core_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<div class="wrapper signup-wrapper">
  <div class="login-container">
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.text_field :name, class: 'login-input', required: true, placeholder: 'Name' %>
      <%= f.email_field :email, class: 'login-input', required: true, placeholder: 'Email' %>
      <%= f.password_field :password, class: 'login-input', required: true, placeholder: 'Password' %>
      <%= f.password_field :password_confirmation, class: 'login-input', required: true, placeholder: 'Password confirmation' %>
      <br>
      <%= f.submit 'Sign up', id: 'submit-button', data: { disable_with: 'Submitting...' } %>
    <% end %>
  </div>
  <ul class="bg-bubbles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
</div>

app/views/users/show.html.erb
<section class="events-wrapper">
  <h1><%= @user.name %>'s Profile</h1>
  <ul class="tabs">
    <li class="active">Created events</li>
    <li>Attended events</li>
  </ul>

  <ul class="tab__content">
    <li class="active">
      <div class="content__wrapper">
        <div class="row">
          <% if @created_events.present? %>
            <p><%= render @created_events %></p>
            <%= will_paginate @created_events, class: "text-center" %>
          <% else %>
            <p>Nothing to see here, yet.</p>
          <% end %>
        </div>
      </div>
    </li>
    <li>
      <div class="content__wrapper">
        <div class="row">
          <% if @attended_events.present? %>
            <p><%= render @attended_events %></p>
            <%= will_paginate @attended_events, class: "text-center" %>
          <% else %>
            <p>Nothing to see here, yet.</p>
          <% end %>
        </div>
      </div>
    </li>
  </ul>
</section>